update env support

diff --git a/utilities/alter b/utilities/alter
--- a/utilities/alter
+++ b/utilities/alter
@@ -7,21 +7,21 @@ if [ $# == 1 ]; then
 fi
 
 if [ $# -ne 2 ]; then
-    echo "Usage alter ENV ARCH"
+    echo "Usage alter ENV MODE"
     exit 0
 fi
 
 if [ -d "$ENV/$1" ]; then
     CURRENT="$ENV/$1/current"
     if [ -d "$CURRENT" ]; then
-        echo "Error: Environment '$1' does not support arch-specific configuration!"
-        exit 1
-    else
         if [ -h "$CURRENT" ]; then
             rm "$CURRENT"
+        else
+            echo "Error: Environment '$1' does not support arch-specific configuration!"
+            exit 1
         fi
-        ln -s "$ENV/$1/$2" "$ENV/$1/current"
     fi
+    ln -s "$ENV/$1/$2" "$ENV/$1/current"
 else
     echo "Unknown Environment: $1"
     exit 1
